pipeline {
    agent any
    parameters {
        gitParameter(name: 'BRANCH', defaultValue: 'main', type: 'BRANCH', branchFilter: 'origin/(.*)')
        string(name: 'PACKAGE_LIST_PATH', defaultValue: 'C:\\project\\repo\\CICDDemo\\config', description: 'Please enter the entire packageList file path.')
        string(name: 'PACKAGE_LIST_NAME', defaultValue: 'PackageList.txt', description: 'Please enter the Package List file name.')
        string(name: 'HEAD_TRACE_NUMBER', defaultValue: '1', description: 'Please enter the trace number of header, sample: 1,2,3.')
		string(name: 'BUILD_VERSION', defaultValue: '1301', description: 'Please enter the build version.')

    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: "*/${params.BRANCH}"]],
                        extensions: [cleanBeforeCheckout(deleteUntrackedNestedRepositories: true)],
                        gitTool: 'Default',
                        userRemoteConfigs: [[credentialsId: 'aed818f8-684e-4616-a429-a8aa5186d90d', url: 'https://github.com/chenweixan/IS']]
                    ])
                }
            }
        }
        stage('Find Changes') {
            steps {
                script {
                    def changedFilesCmd = 'cmd /c "git diff --name-only HEAD HEAD~'
					changedFilesCmd = "${changedFilesCmd}${params.HEAD_TRACE_NUMBER}\""
					echo "${changedFilesCmd}"
                    def changedFiles = powershell(returnStdout: true, script: """& ${changedFilesCmd}""").trim()
                    def outputFile = "${params.PACKAGE_LIST_PATH}/${params.PACKAGE_LIST_NAME}"
                    dir(params.PACKAGE_LIST_PATH) {
                       writeFile encoding: 'UTF-8', text: changedFiles, file: params.PACKAGE_LIST_NAME
                    }
                    echo "Changed files:"
                    echo "${changedFiles}, file location: ${outputFile}."
                }
            }
        }
		stage('Build') {
            steps {
                script {
						bat """
							%SAG_INSTALL_DIR%/common/AssetBuildEnvironment/bin/build.bat -Dbuild.output.dir=C:/project/repo/builds -Dbuild.source.dir=%WORKSPACE% -Denable.build.IS=true
						"""
                }
            }
        }
		stage('Generate The Project Automator template File') {
            steps {
                script {
						bat """
							java -Dconfig.file.path=C:\\project\\repo\\CICDDemo\\config\\config.cnf -jar C:\\project\\xml-tool-1.0-SNAPSHOT-jar-with-dependencies.jar C:\\project\\repo\\CICDDemo\\config\\PackageList.txt C:\\project\\repo\\CICDDemo\\config\\ProjectAutomator_NonProd.xml ENV_SIT %BUILD_VERSION%
						"""
                }
            }
        }
		stage('Populate The Project Automator File with details') {
            steps {
                script {
						bat """
							%SAG_INSTALL_DIR%/common/lib/ant/bin/ant.bat -f C:/project/repo/CICDDemo/config/UpdateAutomator_NonProd.xml -Dbuild.version=%BUILD_VERSION%
						"""
                }
            }
        }
    }
}
